"""
AgenticExecutor — AI-generated analysis scripts executed in a secure sandbox.

What this does
--------------
During a code review, an LLM can generate a short Python *analysis script*
tailored to the specific PR — for example:

    - Run the changed module's own test suite to detect regressions.
    - Parse a config file introduced in the PR and validate its schema.
    - Import a Python module from the PR and call a function with safe inputs
      to verify it doesn't raise unexpectedly.

These scripts are then executed **inside a :class:`DockerSandbox`** container
so that malicious or buggy code can never affect the host.

Security model
--------------
1. Script is generated by the LLM from a restricted prompt (no networking).
2. Script is written to a temp file that is mounted **read-only** in the
   container at ``/sandbox/script.py``.
3. The container has **no network** access, a **read-only** repo mount, and
   runs as ``nobody`` with all Linux capabilities dropped.
4. A strict wall-clock timeout kills the container if the script hangs.
5. The container is unconditionally destroyed after each run.

Usage
-----
    executor = AgenticExecutor(sandbox=DockerSandbox())
    result = executor.execute_analysis(
        pr_diff="...",
        repo_path="/path/to/repo",
        pr_number=42,
    )
    print(result.findings_summary)
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Optional, TYPE_CHECKING

from core.logger import get_logger, generate_request_id
from llm.router import LLMRouter
from llm.schemas import LLMRequest

if TYPE_CHECKING:
    from analyzers.docker_sandbox import DockerSandbox

logger = get_logger("analyzers.agentic_executor")

# Maximum characters of diff to pass to the LLM for script generation
_MAX_DIFF_CHARS = 8_000



_SCRIPT_GEN_SYSTEM_PROMPT_2="""
Your Role:
You are a Senior Static Analysis Engineer specializing in secure code review, Python AST analysis, and deterministic tooling for CI/CD pipelines.

Short basic instruction:
Generate a single self-contained Python 3.11 static-analysis script for secure pull request review.

What you should do:
Generate exactly one Python 3.11 script that:

- Analyzes the provided pull request (PR) diff.
- Reads repository source files from the read-only directory `/repo`.
- Detects potential:
  - Bugs
  - Security vulnerabilities
  - Code quality issues
- Produces deterministic results.
- Prints all findings as a JSON array to stdout.
- Exits with status code 0 on successful execution, regardless of whether findings exist.

Output Requirements:
Return ONLY the Python script enclosed within:

```python
...
```

Do NOT include:
- Markdown outside the code block
- Explanations
- Comments before or after the code block
- Example output
- Additional text

Finding Schema:
Every finding MUST be a JSON object with the exact structure:

{
  "file": "relative/path.py",
  "line": 123,
  "severity": "error|warning|info",
  "message": "Concise human-readable description"
}

The final stdout output MUST be:

[
  {...},
  {...}
]

or

[]

Implementation Requirements:
The generated script should:

- Parse and analyze the supplied PR diff.
- Inspect relevant files inside `/repo`.
- Use AST-based analysis whenever possible instead of regular expressions.
- Gracefully handle:
  - Missing files
  - Syntax errors
  - Encoding errors
  - Unexpected input
- Never crash because of malformed input.
- Produce deterministic output for identical inputs.
- Avoid duplicate findings.
- Keep findings concise and actionable.
- Prefer high-signal findings over speculative ones.

STRICT Constraints:
The generated script MUST satisfy ALL of the following.

Runtime
- Python 3.11
- Maximum 200 lines of code
- Finish within 30 seconds
- Exit code 0 on success

Filesystem
- Read files ONLY from `/repo`
- Never modify files
- Never create files
- Never delete files

Security
The script MUST NOT use:

- socket
- urllib
- urllib3
- requests
- httpx
- aiohttp
- ftplib
- smtplib
- paramiko
- subprocess
- multiprocessing
- os.system
- pty
- ctypes
- eval
- exec
- compile

Imports
Only the following modules are permitted:

- ast
- json
- pathlib
- re
- fnmatch
- textwrap
- collections
- itertools
- typing
- dataclasses
- enum

No other imports are allowed.

Quality Requirements:
- Keep the implementation simple and readable.
- Avoid unnecessary abstraction.
- Avoid dead code.
- Use descriptive variable names.
- Minimize memory usage.
- Ensure deterministic ordering of findings.
- Do not emit duplicate findings.
- Handle edge cases safely.

Your Goal:
Produce a robust, deterministic, secure, CI-friendly static analysis script that strictly follows every constraint above without exception.

Constraint:
If any required input (such as the PR diff format or invocation method) is missing, make only the minimum reasonable assumptions necessary while remaining fully compliant with all constraints.

Context:
Assume the script will run inside an automated secure code review system with a read-only repository mounted at `/repo`, where any violation of the above constraints will cause the generated solution to be rejected.
"""

# The system prompt that constrains what the LLM-generated script can do
_SCRIPT_GEN_SYSTEM_PROMPT = """\
You are a static-analysis script generator for a secure code review system.

Your ONLY job is to write a short Python 3.11 script that:
1. Analyses the provided PR diff to identify potential bugs, security issues,
   or code quality problems.
2. Reads source files from /repo (read-only mount — DO NOT write anything).
3. Prints findings as a JSON array to stdout. Each finding must be a dict:
   {"file": "path", "line": 123, "severity": "error|warning|info",
    "message": "Concise description"}
4. Exits with code 0 on success (even if findings were found).

STRICT CONSTRAINTS — your script MUST follow these or it will be rejected:
- No network access (socket, urllib, requests, httpx, etc. are not permitted).
- No subprocess calls, os.system, or shell execution.
- No file writes of any kind.
- No imports outside Python stdlib + these approved packages:
    ast, json, pathlib, re, fnmatch, textwrap, collections, itertools,
    typing, dataclasses, enum.
- Maximum 200 lines of code.
- Must complete within 30 seconds.

Respond with ONLY the Python script inside ```python ... ``` fences.
Do NOT include any explanation outside the code fences.
"""


@dataclass
class AgenticAnalysisResult:
    """Result from an :class:`AgenticExecutor` run.

    Attributes:
        findings: List of finding dicts parsed from the script output.
            Each dict has: file, line, severity, message.
        script: The Python script that was generated and executed.
        stdout: Raw stdout from the sandbox execution.
        stderr: Raw stderr from the sandbox execution.
        script_exit_code: Exit code from the sandbox container.
        success: True if the analysis completed without errors.
        error: Human-readable error message if execution failed.
        findings_summary: Pre-formatted Markdown summary of findings.
        sandbox_available: True if Docker was available and used.
    """

    findings: list[dict] = field(default_factory=list)
    script: str = ""
    stdout: str = ""
    stderr: str = ""
    script_exit_code: int = -1
    success: bool = False
    error: Optional[str] = None
    findings_summary: str = ""
    sandbox_available: bool = False

    def to_markdown(self) -> str:
        """Format findings as a Markdown comment block.

        Returns:
            Markdown string suitable for GitHub PR comment injection.
        """
        if not self.success:
            return f"> ⚠️ **AgenticExecutor** failed: {self.error or 'Unknown error'}"

        if not self.findings:
            return "> ✅ **AgenticExecutor** found no issues in the runtime analysis."

        lines = ["### 🤖 Runtime Analysis Findings\n"]
        lines.append("| File | Line | Severity | Message |")
        lines.append("|------|------|----------|---------|")
        for f in self.findings[:20]:
            lines.append(
                f"| `{f.get('file', '?')}` | {f.get('line', '?')} | "
                f"**{f.get('severity', 'info').upper()}** | {f.get('message', '')[:100]} |"
            )
        if len(self.findings) > 20:
            lines.append(f"| ... | ... | ... | +{len(self.findings) - 20} more findings |")
        return "\n".join(lines)


class AgenticExecutor:
    """Generate and safely execute AI-written analysis scripts in Docker.

    Args:
        sandbox: A configured :class:`~analyzers.docker_sandbox.DockerSandbox`
            instance.  If ``None``, a default sandbox is created automatically.
        router: An :class:`~llm.router.LLMRouter` instance.  Defaults to a
            fresh instance using the global settings.
        script_timeout: Per-script execution timeout in seconds.
    """

    def __init__(
        self,
        sandbox: Optional["DockerSandbox"] = None,
        router: Optional[LLMRouter] = None,
        script_timeout: int = 30,
    ) -> None:
        from analyzers.docker_sandbox import DockerSandbox as _DockerSandbox

        self.sandbox = sandbox or _DockerSandbox(timeout=script_timeout)
        self.router = router or LLMRouter()
        self.script_timeout = script_timeout

    # ── Public API ───────────────────────────────────────────────────────

    def execute_analysis(
        self,
        pr_diff: str,
        repo_path: str,
        pr_number: int,
        changed_files: Optional[list[str]] = None,
    ) -> AgenticAnalysisResult:
        """Generate an analysis script via LLM and run it in a sandbox.

        Steps:
            1. Check Docker availability; fall back gracefully if absent.
            2. Ask the LLM to write a static-analysis script for this diff.
            3. Validate the script for obvious unsafe patterns.
            4. Execute the script in the sandbox.
            5. Parse JSON findings from stdout.

        Args:
            pr_diff: The raw unified diff text from the PR.
            repo_path: Absolute path to the cloned repository on the host.
            pr_number: PR number (used for logging only).
            changed_files: Optional list of changed file paths to focus on.

        Returns:
            :class:`AgenticAnalysisResult` — always, even on failure.
        """
        request_id = generate_request_id()
        logger.info("[%s] AgenticExecutor: starting for PR #%d", request_id, pr_number)

        # 1. Check Docker availability
        if not self.sandbox.is_available():
            msg = (
                "Docker is not available on this host. "
                "AgenticExecutor requires Docker — install Docker Desktop or "
                "Docker Engine and ensure the daemon is running."
            )
            logger.warning("[%s] %s", request_id, msg)
            return AgenticAnalysisResult(error=msg, sandbox_available=False)

        # 2. Generate the analysis script via LLM
        script = self._generate_script(pr_diff, changed_files, request_id)
        if not script:
            return AgenticAnalysisResult(
                error="LLM failed to generate an analysis script.",
                sandbox_available=True,
            )

        # 3. Validate the script for dangerous patterns
        validation_error = self._validate_script(script)
        if validation_error:
            logger.warning(
                "[%s] AgenticExecutor: script failed validation: %s", request_id, validation_error
            )
            return AgenticAnalysisResult(
                script=script,
                error=f"Generated script failed safety validation: {validation_error}",
                sandbox_available=True,
            )

        # 4. Execute in sandbox
        logger.info("[%s] AgenticExecutor: executing script in sandbox ...", request_id)
        sandbox_result = self.sandbox.run_command(
            command=["python", "/sandbox/script.py"],
            repo_path=repo_path,
            script_content=script,
            timeout=self.script_timeout,
        )

        if sandbox_result.timed_out:
            return AgenticAnalysisResult(
                script=script,
                stdout=sandbox_result.stdout,
                stderr=sandbox_result.stderr,
                script_exit_code=sandbox_result.exit_code,
                error=f"Script timed out after {self.script_timeout}s",
                sandbox_available=True,
                success=False,
            )

        if not sandbox_result.success and sandbox_result.error:
            return AgenticAnalysisResult(
                script=script,
                stdout=sandbox_result.stdout,
                stderr=sandbox_result.stderr,
                script_exit_code=sandbox_result.exit_code,
                error=f"Sandbox error: {sandbox_result.error}",
                sandbox_available=True,
                success=False,
            )

        # 5. Parse findings from stdout
        findings = self._parse_findings(sandbox_result.stdout)
        summary = self._format_summary(findings, sandbox_result)

        logger.info(
            "[%s] AgenticExecutor: complete — %d findings, exit_code=%d",
            request_id, len(findings), sandbox_result.exit_code,
        )

        return AgenticAnalysisResult(
            findings=findings,
            script=script,
            stdout=sandbox_result.stdout,
            stderr=sandbox_result.stderr,
            script_exit_code=sandbox_result.exit_code,
            success=True,
            findings_summary=summary,
            sandbox_available=True,
        )

    # ── Private helpers ──────────────────────────────────────────────────

    def _generate_script(
        self,
        pr_diff: str,
        changed_files: Optional[list[str]],
        request_id: str,
    ) -> str:
        """Ask the LLM to write a focused analysis script for this PR."""
        # Truncate diff to avoid exceeding context limits
        truncated_diff = pr_diff[:_MAX_DIFF_CHARS]
        if len(pr_diff) > _MAX_DIFF_CHARS:
            truncated_diff += f"\n\n[Diff truncated at {_MAX_DIFF_CHARS} chars]"

        files_hint = ""
        if changed_files:
            files_hint = (
                "\n\nChanged files in this PR:\n" +
                "\n".join(f"  - {f}" for f in changed_files[:30])
            )

        user_content = (
            f"Generate an analysis script for the following PR diff."
            f"{files_hint}\n\n"
            f"```diff\n{truncated_diff}\n```"
        )

        llm_request = LLMRequest(
            task_type="code_review",
            messages=[
                {"role": "system", "content": _SCRIPT_GEN_SYSTEM_PROMPT},
                {"role": "user", "content": user_content},
            ],
            temperature=0.1,  # Low temperature for deterministic code generation
            metadata={"request_id": request_id},
        )

        response = self.router.generate(llm_request)
        if not response.success:
            logger.error("[%s] LLM script generation failed: %s", request_id, response.error)
            return ""

        return self._extract_code(response.content)

    def _extract_code(self, llm_output: str) -> str:
        """Extract the Python code from LLM output (strips markdown fences)."""
        # Try ```python ... ```
        match = re.search(r"```python\s*(.*?)```", llm_output, re.DOTALL)
        if match:
            return match.group(1).strip()
        # Try bare ``` ... ```
        match = re.search(r"```\s*(.*?)```", llm_output, re.DOTALL)
        if match:
            return match.group(1).strip()
        # Assume the whole response is code
        return llm_output.strip()

    def _validate_script(self, script: str) -> Optional[str]:
        """Basic static safety check before executing the script.

        Checks for forbidden patterns that should never appear in an analysis
        script:
          - Network socket usage
          - Subprocess / os.system calls
          - File writes

        Args:
            script: The Python source code to validate.

        Returns:
            Error string if validation fails, ``None`` if script is safe.
        """
        forbidden_patterns = [
            (r"\bimport\s+socket\b", "network socket usage"),
            (r"\bimport\s+subprocess\b", "subprocess usage"),
            (r"\bos\.system\b", "os.system call"),
            (r"\bos\.popen\b", "os.popen call"),
            (r"\bsubprocess\.", "subprocess usage"),
            (r"\bopen\s*\(.*,\s*['\"]w['\"]", "file write detected"),
            (r"\bopen\s*\(.*,\s*['\"]a['\"]", "file append detected"),
            (r"\bimport\s+requests\b", "requests (network) import"),
            (r"\bimport\s+urllib\b", "urllib (network) import"),
            (r"\bimport\s+httpx\b", "httpx (network) import"),
            (r"\bimport\s+aiohttp\b", "aiohttp (network) import"),
            (r"\beval\s*\(", "eval() usage (code injection risk)"),
            (r"\bexec\s*\(", "exec() usage (code injection risk)"),
            (r"__import__\s*\(", "__import__ usage"),
        ]

        for pattern, reason in forbidden_patterns:
            if re.search(pattern, script, re.IGNORECASE):
                return f"Forbidden pattern detected: {reason}"

        # Check line count
        lines = script.splitlines()
        if len(lines) > 200:
            return f"Script exceeds 200 line limit ({len(lines)} lines)"

        return None

    def _parse_findings(self, stdout: str) -> list[dict]:
        """Parse JSON findings from the script's stdout.

        The script is expected to print a JSON array of finding dicts.
        Handles partial output gracefully.

        Args:
            stdout: Raw stdout captured from the sandbox container.

        Returns:
            List of validated finding dicts (may be empty).
        """
        if not stdout.strip():
            return []

        # Try to find a JSON array anywhere in stdout
        match = re.search(r"\[.*\]", stdout, re.DOTALL)
        if not match:
            logger.debug("AgenticExecutor: no JSON array found in script output")
            return []

        try:
            raw = json.loads(match.group(0))
            if not isinstance(raw, list):
                return []
            findings = []
            for item in raw:
                if not isinstance(item, dict):
                    continue
                findings.append({
                    "file": str(item.get("file", "unknown")),
                    "line": int(item.get("line", 0)),
                    "severity": str(item.get("severity", "info")).lower(),
                    "message": str(item.get("message", "")),
                })
            return findings
        except (json.JSONDecodeError, ValueError) as exc:
            logger.warning("AgenticExecutor: failed to parse findings JSON: %s", exc)
            return []

    def _format_summary(self, findings: list[dict], sandbox_result) -> str:
        """Build a plain-text summary for logging."""
        errors = sum(1 for f in findings if f.get("severity") == "error")
        warnings = sum(1 for f in findings if f.get("severity") == "warning")
        return (
            f"{len(findings)} findings ({errors} errors, {warnings} warnings) — "
            f"exit_code={sandbox_result.exit_code} "
            f"duration={sandbox_result.duration_seconds:.1f}s"
        )
