"""
DockerSandbox — isolated Docker container execution for DevAssist-AI.

Why this exists
---------------
When a PR contains code that will be *run* as part of analysis (e.g. a
script generated by the AgenticExecutor), executing it on the host machine
is a critical security risk — malicious code could exfiltrate secrets,
corrupt files, or establish a reverse shell.

DockerSandbox wraps `docker` SDK calls to:
  1. Spin up a disposable, read-only container with the cloned repo mounted.
  2. Run a single command (linter, test runner, AI-generated script) inside it.
  3. Capture stdout / stderr with a hard CPU + wall-clock timeout.
  4. Destroy the container unconditionally in the ``finally`` block.

Security hardening applied
--------------------------
- ``network_disabled=True``          No outbound network access inside container.
- ``read_only=True`` filesystem      Container cannot write to the mounted repo.
- ``mem_limit`` / ``nano_cpus``      Resource caps prevent fork-bombs / DoS.
- ``cap_drop=["ALL"]``               All Linux capabilities dropped.
- ``security_opt=["no-new-privileges:true"]``  Prevents privilege escalation.
- ``user="nobody"``                  Runs as unprivileged user (UID 65534).
- Auto-remove on exit                No orphaned containers accumulate.

Usage
-----
    sandbox = DockerSandbox(image="python:3.11-slim")
    result = sandbox.run_command(
        command=["python", "-m", "pytest", "tests/"],
        repo_path="/path/to/cloned/repo",
    )
    if result.success:
        print(result.stdout)
    else:
        print("Error:", result.error)
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from typing import Optional

from core.logger import get_logger

logger = get_logger("analyzers.docker_sandbox")

# Defaults — can be overridden per-call or via env settings
_DEFAULT_IMAGE = "python:3.11-slim"
_DEFAULT_TIMEOUT = 60          # seconds
_DEFAULT_MEM_LIMIT = "256m"    # Docker memory limit string
_DEFAULT_CPU_QUOTA = 0.5       # fraction of one CPU core


@dataclass
class SandboxRunResult:
    """Result from a single sandbox execution.

    Attributes:
        stdout: Captured standard output from the command.
        stderr: Captured standard error from the command.
        exit_code: Process exit code returned by the container.
        duration_seconds: Wall-clock seconds the command took.
        container_id: Short Docker container ID used for this run.
        success: True when exit_code == 0 and no unhandled error occurred.
        error: Human-readable error message if the sandbox itself failed.
        timed_out: True when the command was killed due to exceeding timeout.
    """

    stdout: str = ""
    stderr: str = ""
    exit_code: int = -1
    duration_seconds: float = 0.0
    container_id: str = ""
    success: bool = False
    error: Optional[str] = None
    timed_out: bool = False


class DockerSandbox:
    """Isolated Docker container execution environment.

    One instance can be reused for multiple :meth:`run_command` calls.
    Each call creates and destroys its own container — there is no persistent
    warm container — to avoid state accumulation between reviews.

    Args:
        image: Docker image to use. Must already be pulled on the host.
        timeout: Default wall-clock timeout in seconds.  Can be overridden
            per ``run_command`` call.
        mem_limit: Docker memory limit string (e.g. ``"256m"``, ``"1g"``).
        cpu_quota: CPU quota as fraction of one core (0.0–1.0).
    """

    def __init__(
        self,
        image: str = _DEFAULT_IMAGE,
        timeout: int = _DEFAULT_TIMEOUT,
        mem_limit: str = _DEFAULT_MEM_LIMIT,
        cpu_quota: float = _DEFAULT_CPU_QUOTA,
    ) -> None:
        self.image = image
        self.timeout = timeout
        self.mem_limit = mem_limit
        self.cpu_quota = cpu_quota
        self._client = None  # Lazy-init docker client

    # ── Public API ───────────────────────────────────────────────────────

    def is_available(self) -> bool:
        """Return True if Docker daemon is reachable and the image exists.

        Safe to call at startup — never raises; returns False on any error.
        """
        try:
            client = self._get_client()
            client.ping()
            client.images.get(self.image)
            return True
        except Exception as exc:
            logger.debug("Docker not available: %s", exc)
            return False

    def run_command(
        self,
        command: list[str],
        repo_path: str,
        *,
        timeout: Optional[int] = None,
        env_vars: Optional[dict[str, str]] = None,
        workdir: str = "/repo",
        script_content: Optional[str] = None,
        extra_volumes: Optional[dict] = None,
    ) -> SandboxRunResult:
        """Run *command* inside an isolated Docker container.

        The cloned repository is mounted read-only at ``/repo`` inside the
        container.  An optional *script_content* string can be written to a
        temp file that is also mounted into the container.

        Args:
            command: Command and arguments to execute, e.g.
                ``["python", "-m", "ruff", "check", "."]``.
            repo_path: Absolute path to the cloned repository on the host.
                Mounted read-only at ``/repo``.
            timeout: Per-call timeout override in seconds.
            env_vars: Extra environment variables to pass to the container.
            workdir: Working directory inside the container.
            script_content: If provided, this string is written to a
                temporary file and mounted at ``/sandbox/script.py`` so
                the command can reference it (e.g. for AgenticExecutor).
            extra_volumes: Additional volume mappings to pass through.

        Returns:
            :class:`SandboxRunResult` — always, even on timeout or error.
        """
        effective_timeout = timeout or self.timeout
        container_id = f"devassist-{uuid.uuid4().hex[:12]}"
        start = time.time()

        try:
            client = self._get_client()
        except ImportError:
            return SandboxRunResult(
                error="docker-py is not installed. Run: uv add docker",
                exit_code=-1,
            )
        except Exception as exc:
            return SandboxRunResult(
                error=f"Cannot connect to Docker daemon: {exc}",
                exit_code=-1,
            )

        # Build volume map
        volumes: dict = {
            repo_path: {"bind": "/repo", "mode": "ro"},
        }
        if extra_volumes:
            volumes.update(extra_volumes)

        # Write optional inline script
        _tmp_script_path = None
        if script_content is not None:
            import tempfile, os
            tmp = tempfile.NamedTemporaryFile(
                mode="w", suffix=".py", delete=False, encoding="utf-8"
            )
            tmp.write(script_content)
            tmp.flush()
            tmp.close()
            _tmp_script_path = tmp.name
            volumes[_tmp_script_path] = {"bind": "/sandbox/script.py", "mode": "ro"}

        environment = env_vars or {}
        # Always pass these safety env vars
        environment.setdefault("PYTHONDONTWRITEBYTECODE", "1")
        environment.setdefault("PYTHONUNBUFFERED", "1")

        nano_cpus = int(self.cpu_quota * 1_000_000_000)

        container = None
        try:
            logger.info(
                "DockerSandbox: starting container '%s' (image=%s, timeout=%ds)",
                container_id, self.image, effective_timeout,
            )

            container = client.containers.run(
                image=self.image,
                command=command,
                name=container_id,
                volumes=volumes,
                working_dir=workdir,
                environment=environment,
                # ── Security hardening ──────────────────────────
                network_disabled=True,
                read_only=True,
                mem_limit=self.mem_limit,
                nano_cpus=nano_cpus,
                cap_drop=["ALL"],
                security_opt=["no-new-privileges:true"],
                user="nobody",
                # ── Lifecycle ───────────────────────────────────
                detach=True,
                auto_remove=False,
            )

            # Wait with timeout
            try:
                exit_result = container.wait(timeout=effective_timeout)
                exit_code = exit_result.get("StatusCode", -1)
                timed_out = False
            except Exception:
                logger.warning("DockerSandbox: container '%s' timed out — killing", container_id)
                try:
                    container.kill()
                except Exception:
                    pass
                exit_code = -1
                timed_out = True

            # Collect output
            try:
                stdout = container.logs(stdout=True, stderr=False).decode("utf-8", errors="replace")
                stderr = container.logs(stdout=False, stderr=True).decode("utf-8", errors="replace")
            except Exception:
                stdout, stderr = "", ""

            duration = time.time() - start
            logger.info(
                "DockerSandbox: container '%s' exit_code=%d duration=%.2fs timed_out=%s",
                container_id, exit_code, duration, timed_out,
            )

            return SandboxRunResult(
                stdout=stdout,
                stderr=stderr,
                exit_code=exit_code,
                duration_seconds=duration,
                container_id=container_id,
                success=(exit_code == 0 and not timed_out),
                timed_out=timed_out,
            )

        except Exception as exc:
            duration = time.time() - start
            logger.error("DockerSandbox: unexpected error for '%s': %s", container_id, exc)
            return SandboxRunResult(
                exit_code=-1,
                duration_seconds=duration,
                container_id=container_id,
                error=str(exc),
            )

        finally:
            # Always destroy the container to prevent resource leaks
            if container is not None:
                try:
                    container.remove(force=True)
                    logger.debug("DockerSandbox: removed container '%s'", container_id)
                except Exception as rm_exc:
                    logger.warning("DockerSandbox: failed to remove '%s': %s", container_id, rm_exc)

            # Clean up temp script file
            if _tmp_script_path is not None:
                try:
                    import os
                    os.unlink(_tmp_script_path)
                except Exception:
                    pass

    def pull_image(self) -> bool:
        """Pull the configured Docker image if not already present.

        Returns:
            True on success, False on failure.
        """
        try:
            client = self._get_client()
            logger.info("DockerSandbox: pulling image '%s' ...", self.image)
            client.images.pull(self.image)
            logger.info("DockerSandbox: image '%s' pulled successfully", self.image)
            return True
        except Exception as exc:
            logger.error("DockerSandbox: failed to pull image '%s': %s", self.image, exc)
            return False

    # ── Internal ─────────────────────────────────────────────────────────

    def _get_client(self):
        """Lazy-initialise and cache the Docker SDK client."""
        if self._client is None:
            try:
                import docker
            except ImportError as exc:
                raise ImportError(
                    "docker-py is not installed. Run: uv add docker"
                ) from exc
            self._client = docker.from_env()
        return self._client
